services:

  backend:
    build: ../backend
    container_name: backend_api
    ports:
      - "5001:5000"
    volumes:
      - backend_data:/data
    networks:
      - monitoring_net
    environment:
      FLASK_ENV: development

  frontend:
    build: ../frontend
    container_name: frontend_app
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - monitoring_net
    environment:
      API_URL: "http://backend:5001/api/metrics"
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      FLASK_ENV: development

networks:
  monitoring_net:
    driver: bridge

volumes:
  backend_data:
